spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: shopping-cart-service
      key-deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  jpa:
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
